// vue/src/components/Todo.vue
<template>
    <section class="todoapp" v-cloak>
			<header class="header">
				<h1>todos</h1>
				<input class="new-todo" autofocus autocomplete="off" placeholder="What needs to be done?" v-model="newTodo" @keyup.enter="addTodo">
			</header>
			<section class="main" v-show="todos.length">
				<input id="toggle-all" class="toggle-all" type="checkbox" v-model="allDone">
				<label for="toggle-all">Mark all as complete</label>
				<ul class="todo-list">
					<li class="todo" v-for="todo in filteredTodos" :key="todo.id" :class="{completed: todo.completed, editing: todo == editedTodo}">
						<div class="view">
							<input class="toggle" type="checkbox" v-model="todo.completed">
							<label @dblclick="editTodo(todo)">{{todo.title}}</label>
							<button class="destroy" @click="removeTodo(todo)"></button>
						</div>
						<input class="edit" type="text" v-model="todo.title" v-todo-focus="todo == editedTodo" @blur="doneEdit(todo)" @keyup.enter="doneEdit(todo)" @keyup.esc="cancelEdit(todo)">
					</li>
				</ul>
			</section>
			<footer class="footer" v-show="todos.length">
				<span class="todo-count">
					<strong v-text="remaining"></strong> {{pluralize('item', remaining)}} left
				</span>
				<ul class="filters">
                    <li><router-link class="nav-link" :to="{name:'home', params: {visibility: 'all'} }" :class="{selected: visibility == 'all'}">All</router-link></li>
					<li><router-link class="nav-link" :to="{name:'home', params: {visibility: 'active'} }" :class="{selected: visibility == 'active'}">Active</router-link></li>
                    <li><router-link class="nav-link" :to="{name:'home', params: {visibility: 'completed'} }" :class="{selected: visibility == 'completed'}">Completed</router-link></li>
				</ul>
				<button class="clear-completed" @click="removeCompleted" v-show="todos.length > remaining">
					Clear completed
				</button>
			</footer>
		</section>
</template>


<script>
/* eslint-disable */
import todoStorage from './TodoStore'

var filters = {
	all: function (todos) {
		return todos;
	},
	active: function (todos) {
		return todos.filter(function (todo) {
			return !todo.completed;
		});
	},
	completed: function (todos) {
    	return todos.filter(function (todo) {
			return todo.completed;
		});
	}
};

export default {
    name: 'Todo',
    // app initial state
    data: function() {
	    return {
            todos: todoStorage.fetch(),
            newTodo: '',
            editedTodo: null,
            visibility: 'all' // default value
        }
	},
    // watch todos change for localStorage persistence
	watch: {
		todos: {
			deep: true,
			handler: todoStorage.save
		},
        // We initialise the visibility once the route is initialised
        $route: function(){
            this.initVisibility();

        }
	},

	// computed properties
	// http://vuejs.org/guide/computed.html
	computed: {
		filteredTodos: function () {
			return filters[this.visibility](this.todos);
		},
		remaining: function () {
			return filters.active(this.todos).length;
		},
		allDone: {
			get: function () {
				return this.remaining === 0;
			},
			set: function (value) {
				this.todos.forEach(function (todo) {
					todo.completed = value;
				});
			}
		}
	},
	// methods that implement data logic.
	// note there's no DOM manipulation here at all.
	methods: {
		pluralize: function (word, count) {
			return word + (count === 1 ? '' : 's');
		},
		addTodo: function () {
    		var value = this.newTodo && this.newTodo.trim();
			if (!value) {
				return;
			}
			this.todos.push({ id: this.todos.length + 1, title: value, completed: false });
			this.newTodo = '';
		},

		removeTodo: function (todo) {
			var index = this.todos.indexOf(todo);
			this.todos.splice(index, 1);
		},

		editTodo: function (todo) {
			this.beforeEditCache = todo.title;
			this.editedTodo = todo;
		},

		doneEdit: function (todo) {
			if (!this.editedTodo) {
				return;
			}
			this.editedTodo = null;
			todo.title = todo.title.trim();
			if (!todo.title) {
				this.removeTodo(todo);
			}
		},

		cancelEdit: function (todo) {
			this.editedTodo = null;
			todo.title = this.beforeEditCache;
		},

		removeCompleted: function () {
			this.todos = filters.active(this.todos);
		},

        initVisibility: function(){
            var visibilityConfig = "all";
            if(this.$route.params.visibility && ['all', 'active', 'completed'].indexOf(this.$route.params.visibility) != -1)
            {
                visibilityConfig = this.$route.params.visibility;
            }
            this.visibility = visibilityConfig;
        }
	},

	// a custom directive to wait for the DOM to be updated
	// before focusing on the input field.
	// http://vuejs.org/guide/custom-directive.html
	directives: {
		'todo-focus': function (el, binding) {
			if (binding.value) {
				el.focus();
			}
		}
	}
}
</script>

// angular/src/app/todo/todo.component.ts
import { Component, OnInit } from '@angular/core';
import { Router, ActivatedRoute, ParamMap } from '@angular/router';
import {TodostoreService, Todo} from '../services/todostore.service';

@Component({
  selector: 'app-todo',
  templateUrl: './todo.component.html',
  styleUrls: ['./todo.component.css']
})
export class TodoComponent implements OnInit {
  public todoStore: TodostoreService;
  public newTodoText = '';
  public editedTodo?: Todo;
  public toggleall: boolean;
  public visibility: String;
  public filters: Map<String, Function>;

  get filteredTodos() {
	var filterFct = this.filters.get(this.visibility);
	if(filterFct)
	{
		return filterFct(this.todoStore.todos);		
	}
	return this.todoStore.todos;
 }

  constructor(todoStore: TodostoreService,public route: ActivatedRoute) {
		this.todoStore = todoStore;
		this.toggleall = true;
		this.editedTodo = undefined;
		this.visibility = "all";
		this.filters = new Map<String, Function>(
			[
				["all", function (todos: Array<Todo>) {
					return todos;
				}],
				["active", function (todos: Array<Todo>) {
					return todos.filter(function (todo) {
						return !todo.completed;
					});
				}],
				["completed", function (todos: Array<Todo>) {
					return todos.filter(function (todo) {
						return todo.completed;
					});
				}]
			]
		)
	}

	ngOnInit() {
		  this.route.queryParams.subscribe(
			params => {
				this.initVisibility();
			}
		  )
	  }

	stopEditing(todo: Todo, editedTitle: string) {
		todo.title = editedTitle;
		todo.editing = false;
	}

	cancelEditingTodo(todo: Todo) {
		todo.editing = false;
	}

	updateEditingTodo(todo: Todo, editedTitle: string) {
		editedTitle = editedTitle.trim();
		todo.editing = false;

		if (editedTitle.length === 0) {
			return this.todoStore.remove(todo);
		}

		todo.title = editedTitle;
	}

	routeIs(targetVisibility: String){
		console.log("query params",this.route.snapshot.queryParams);
		console.log("visibility target", targetVisibility);
		
		return  ( Object.keys(this.route.snapshot.queryParams).length === 0 && targetVisibility == "") || 
				this.route.snapshot.queryParams.visibility == targetVisibility;
	}

	editTodo(todo: Todo) {
		todo.editing = true;
	}

	removeCompleted() {
		this.todoStore.removeCompleted();
	}

	toggleCompletion(todo: Todo) {
		this.todoStore.toggleCompletion(todo);
	}

	remove(todo: Todo){
		this.todoStore.remove(todo);
	}

	public addTodo() {
		if (this.newTodoText.trim().length) {
			this.todoStore.add(this.newTodoText);
			this.newTodoText = '';
		}
	}

	initVisibility(){
		var visibilityConfig = "all";
		var visibilityParam = this.route.snapshot.queryParams.visibility;
		if( visibilityParam && ['all', 'active', 'completed'].indexOf(visibilityParam) != -1)
		{
			visibilityConfig = visibilityParam;
		}
		this.visibility = visibilityConfig;
	}

}

<section class="todoapp">
	<header class="header">
		<h1>todos</h1>
		<input class="new-todo" placeholder="What needs to be done?" autofocus="" [(ngModel)]="newTodoText" (keyup.enter)="addTodo()">
	</header>
    
	<section class="main" *ngIf="todoStore.todos.length > 0">
		<input id="toggle-all" class="toggle-all" type="checkbox" *ngIf="todoStore.todos.length" #toggleall [checked]="todoStore.allCompleted()" (click)="todoStore.setAllTo(toggleall.checked)">
		<ul class="todo-list">
			<li *ngFor="let todo of filteredTodos" [class.completed]="todo.completed" [class.editing]="todo.editing">
				<div class="view">
					<input class="toggle" type="checkbox" (click)="toggleCompletion(todo)" [checked]="todo.completed">
					<label (dblclick)="editTodo(todo)">{{todo.title}}</label>
					<button class="destroy" (click)="remove(todo)"></button>
				</div>
				 <input class="edit" *ngIf="todo.editing" [value]="todo.title" #editedTodo (blur)="stopEditing(todo, editedTodo.value)" (keyup.enter)="updateEditingTodo(todo, editedTodo.value)" (keyup.escape)="cancelEditingTodo(todo)"> 
			</li>
		</ul>
	</section> 

	<footer class="footer" *ngIf="todoStore.todos.length > 0">
		<span class="todo-count"><strong>{{todoStore.getRemaining().length}}</strong> {{todoStore.getRemaining().length == 1 ? 'item' : 'items'}} left</span>
		<ul class="filters">
			<li>
				<a [ngClass]="{selected: routeIs('') || routeIs('all')} "  [routerLink]="['/']" [queryParams]="{visibility: 'all'}">All</a>
			</li>
			<li>
				<a [ngClass]="{selected: routeIs('active')}" [routerLink]="['/']" [queryParams]="{visibility: 'active'}" >Active</a>
			</li>
			<li>
				<a [ngClass]="{selected: routeIs('completed')}"  [routerLink]="['/']" [queryParams]="{visibility: 'completed'}">Completed</a>
			</li>
		</ul>
		<button class="clear-completed" *ngIf="todoStore.getCompleted().length > 0" (click)="removeCompleted()">Clear completed</button>
	</footer> 
</section>
